### ISSUE TITLE
header validationnnnot really...

### ISSUE THREAD

**Issue by bansp** [KorAP/KorAP-XML-TEI#3]
I'm looking at a fragment of the Gingko corpus header from https://github.com/KorAP/KorAP-XML-Krill/blob/master/t/real/corpus/Gingko/ATZ07/JAN/00001/header.xml :

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="header.rng"
            type="application/xml"
            schematypens="http://relaxng.org/ns/structure/1.0"?>
<!DOCTYPE idsCorpus PUBLIC "-//IDS//DTD IDS-XCES 1.0//EN"
          "http://corpora.ids-mannheim.de/idsxces1/DTD/ids.xcesdoc.dtd">
<idsHeader TEIform="teiHeader" pattern="text" status="new" type="text" version="1.0">
    <fileDesc>
        <titleStmt>
            <textSigle>ATZ07/JAN.00001</textSigle>
            <t.title assemblage="external">ATZ07/JAN.00001 ATZ - Automobiltechnische Zeitschrift, Januar 2007, Nr. 109(1), S. 10-15; Ein neues Energiemanagement-Konzept für das elektrische Bordnetz</t.title>
        </titleStmt>
```

And it seems to me that both schema statements are ornaments, because

- header.rng requires that the root element should be `<header>`
- while the DTD requires that the root element should be `<idsCorpus>`

Fixing the root element in the DTD doesn't move us forward, because then lots of errors crop up that suggest that the DTD hasn't been updated while the XML has evolved.

Removing both schema associations would make the result truer, in a way ;-) 
`<!DOCTYPE idsHeader>` also works, but, naturally, it doesn't do much.

**Comment by Akron** [comment]
You are right - these references seem to be independent of the header source. So as a quick fix I removed them from generation.
