### ISSUE TITLE
tei2korapxml fails for German ICC contribution

### ISSUE THREAD

**Issue by kupietz** [KorAP/KorAP-XML-TEI#4]
Error message:

```
Maybe empty textSigle => skipping this text ...
data=
```

**Comment by kupietz** [comment]
Maybe allow IDs/sigles also as id attributes and provide a parameter to pass  a regular expression  for splitting it into corpus/doc/text-parts?

**Comment by Akron** [comment]
Can you provide an example file as part of the test suite?

**Comment by kupietz** [comment]
https://korap.ids-mannheim.de/gerrit/c/KorAP/KorAP-XML-TEI/+/6473/1/t/data/icc_german_sample.p5.xml

I have already prepared a fix.
