### ISSUE TITLE
tei2korapxml cannot convert standard TEI P5 headers

### ISSUE THREAD

**Issue by kupietz** [KorAP/KorAP-XML-TEI#5]

**Comment by Akron** [comment]
Can you provide an example P5 file to be parsed as part of the test suite?

**Comment by kupietz** [comment]
https://korap.ids-mannheim.de/gerrit/c/KorAP/KorAP-XML-TEI/+/6473/1/t/data/icc_german_sample.p5.xml

I have already prepared a fix.
